### PR TITLE
Separate each tab of plugin in file code

### PR DESCRIPTION
**Pull request by KevinBollore**
@VictorLamoine Ready for review

### CODE REVIEW

**Comment by VictorLamoine** [comment]
- Squash your two commits into one
- Remove `#include <QDebug>`
- Remove comment "// enable or disable panel" and `// Update status label`

```
srv_.request.Axis = "x";
srv_.request.Offset = widget_x_->getParams().Offset;
```
No! (make sure you fill the widget Axis param with X, Y or Z in the X,Y,Z widget constructor)
```
srv_.request = widget_x_->getParams();
```

- `displayStatus(QString::fromStdString("Connecting to service")`
Don't use fromStdString when it's not necessary!


- `setParams()`
Add a comment mentioning it is not allowed to modify the "Axis" (it should be copied from input parameters, but we choose not to)
Call update GUI, we just updated internal values, the GUI must match.

```
void simple_rviz_plugin::XWidget::updateGUI()
 {
   x_offset_->setValue(params_.Offset);
   updateInternalValues();
 }
```
There is no need to call updateInternalValues here.

```
void simple_rviz_plugin::XWidget::updateInternalValues()
 {
   params_.Offset=x_offset_->value();
 }
```
Missing spaces before/after `=` sign

- Remove `getQDoubleSpinBox`

**Comment by VictorLamoine** [comment]
- `void updateGUI()` and `void updateInternalValues(); should be protected

**Comment by KevinBollore** [comment]
@VictorLamoine Done

**Comment by VictorLamoine** [comment]
One last item is not checked, after that we're good to merge.

**Pull request merged**
